version: '3'
services:
        web:
                image: flask_port_v1
                build: .
                ports:
                        - "8019:8019"
                volumes:
                        - ./volumes:/volumes
                        - ./instance:/instance
                restart: unless-stopped
